VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'rails.box'
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.ssh.insert_key = false
end
