#!/bin/bash

## setting up classpath
CP=".:junit.jar:hamcrest.jar"

## creating build directory
mkdir -p build

## compiling into build directory
find bst -name "*.java" | xargs javac -cp $CP -d build

## executing test files
java -cp $CP:build org.junit.runner.JUnitCore bst.BinarySearchTest
