/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'curso' at '19/10/16 15:23' with Gradle 3.1
 *
 * @author curso, @date 19/10/16 15:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
