/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Chrystian Soares' at '24/09/16 10:21' with Gradle 2.6
 *
 * @author Chrystian Soares, @date 24/09/16 10:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
