VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'fnando/hellobits-trusty64'
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.ssh.insert_key = false
  config.vm.define "rails" do |rails|
  end

end

