# coding: utf-8
# frozen_string_literal: true

source "https://rubygems.org"

## cucumber-rails dependency
group :test do
  gem 'nokogiri'
  gem 'cucumber'
  gem 'watir'
  gem 'rspec'
  gem 'webdrivers'
  gem 'cucumber-rails'
end

# gem "rails"
